### PR TITLE
Add post-run-command notify implementation for linux

### PR DESCRIPTION
**Pull request by afbjorklund**
Using `notify-send` instead of `terminal-notifier`, and icons instead of emojis.

Renamed the "notify-macos" to the proper "notify_darwin", so the build works.

Sample notification:

gotestsum-notify-linux-pass

gotestsum-notify-linux-fail

Issue #116

* https://github.com/gotestyourself/gotestsum/issues/74#issuecomment-549133324

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Thank you for the PR! Adding a post run command for linux would be great. I'll try this out myself soon!

**Comment by afbjorklund** [comment]
There is some debugging log spam when invoked, but I kept it the same as the Mac version for now...

```go
        log.Printf("terminal-notifier %#v", args)
```

```go
        log.Printf("notify-send %#v", args)
```

**Comment by afbjorklund** [comment]
In theory this should also work on Windows: http://vaskovsky.net/notify-send/

**Comment by afbjorklund** [comment]
Tested with `GOOS=windows` and Wine + Mono:

wine-pass

wine-fail

https://github.com/vaskovsky/notify-send/releases

**Review by dnephin — APPROVED** [review]
Looks great, thanks!

It wasn't working for me at first, because I had to install `notification-daemon`. I realized the stderr was missing, so I was only able to find the problem by running the command myself.

I pushed a commit to add stdout/stderr output from the notify scripts.

**Pull request merged**
