### PR TITLE
Windows: use golang.org/x/sys to detect Terminal

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dnephin ptal

(looks like it's still used by other dependencies though)

**Comment by dnephin** [comment]
Ya, looks to be still used by `github.com/fatih/color`

**Comment by dnephin** [comment]
Thanks! I rebased to remove the merge config, and updated another dependency while I was at it

**Comment by thaJeztah** [comment]
Thanks! Have one more thing that looks like it can be replaced; let me push that

**Pull request merged**
